[2025-02-09T05:13:02.120+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-09T05:13:02.146+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:12:54.890422+00:00 [queued]>
[2025-02-09T05:13:02.267+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:12:54.890422+00:00 [queued]>
[2025-02-09T05:13:02.268+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-09T05:13:02.283+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_songplays> on 2025-02-09 05:12:54.890422+00:00
[2025-02-09T05:13:02.291+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1460) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T05:13:02.292+0000] {standard_task_runner.py:63} INFO - Started process 1462 to run task
[2025-02-09T05:13:02.291+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_songplays', 'manual__2025-02-09T05:12:54.890422+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpajldrte1']
[2025-02-09T05:13:02.293+0000] {standard_task_runner.py:91} INFO - Job 407: Subtask MusicStream_load_songplays
[2025-02-09T05:13:02.332+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_songplays manual__2025-02-09T05:12:54.890422+00:00 [running]> on host e5529003cf96
[2025-02-09T05:13:02.402+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_songplays' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T05:12:54.890422+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T05:12:54.890422+00:00'
[2025-02-09T05:13:02.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-09T05:13:02.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-09T05:13:02.581+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 68, in load_fact_songplays
    cur.execute(song_select, (row.song, row.artist, row.length))
psycopg2.errors.UndefinedColumn: column dim_songs.artist_id does not exist
LINE 2:     FROM dim_songs JOIN dim_artists ON dim_songs.artist_id =...
                                               ^
HINT:  Perhaps you meant to reference the column "dim_songs.artist_key".

[2025-02-09T05:13:02.590+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_songplays, execution_date=20250209T051254, start_date=20250209T051302, end_date=20250209T051302
[2025-02-09T05:13:02.598+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 407 for task MusicStream_load_songplays (column dim_songs.artist_id does not exist
LINE 2:     FROM dim_songs JOIN dim_artists ON dim_songs.artist_id =...
                                               ^
HINT:  Perhaps you meant to reference the column "dim_songs.artist_key".
; 1462)
[2025-02-09T05:13:02.627+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-09T05:13:02.640+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T05:13:02.643+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
