[2025-02-08T12:23:38.794+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-08T12:23:38.824+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T12:23:38.832+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time scheduled__2025-02-07T00:00:00+00:00 [queued]>
[2025-02-08T12:23:38.833+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-02-08T12:23:38.987+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): MusicStream_load_time> on 2025-02-07 00:00:00+00:00
[2025-02-08T12:23:38.996+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_MusicStreamPipeline', 'MusicStream_load_time', 'scheduled__2025-02-07T00:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpa8cdcdf5']
[2025-02-08T12:23:38.999+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask MusicStream_load_time
[2025-02-08T12:23:38.999+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=182) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-08T12:23:39.000+0000] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2025-02-08T12:23:39.047+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_MusicStreamPipeline.MusicStream_load_time scheduled__2025-02-07T00:00:00+00:00 [running]> on host 35ef1ca6714b
[2025-02-08T12:23:39.124+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Le Huynh Thanh Duong' AIRFLOW_CTX_DAG_ID='etl_MusicStreamPipeline' AIRFLOW_CTX_TASK_ID='MusicStream_load_time' AIRFLOW_CTX_EXECUTION_DATE='2025-02-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-07T00:00:00+00:00'
[2025-02-08T12:23:39.125+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-08T12:23:39.192+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-08T12:23:39.193+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/etls/load.py", line 18, in load_dim_Time
    cur.execute(time_table_insert, (row.day_key, row.start_time, row.hour, row.day, row.week, row.month, row.year, row.weekdate))
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "time_pk"
DETAIL:  Key (day_key)=(2018110100) already exists.

[2025-02-08T12:23:39.201+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_MusicStreamPipeline, task_id=MusicStream_load_time, execution_date=20250207T000000, start_date=20250208T122338, end_date=20250208T122339
[2025-02-08T12:23:39.210+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 148 for task MusicStream_load_time (duplicate key value violates unique constraint "time_pk"
DETAIL:  Key (day_key)=(2018110100) already exists.
; 186)
[2025-02-08T12:23:39.254+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-08T12:23:39.269+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T12:23:39.272+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
